version: "3.9"

services:
  app:
    container_name: julianne-furnishings-frontend
    image: jf
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./src:/app/src
    ports:
      - 5173:5173
    env_file:
      - env/.env.development
